### ISSUE TITLE
The thesis link is unavailable (404)

### ISSUE THREAD

**Issue by coderfromhere** [eelco/gdiff#13]
subj: http://eelco.lempsink.nl/thesis.pdf is not available for reading

**Comment by ddssff** [comment]
Here is a link that works (for the moment.)  It might be good to check this into the source repository.  https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.182.1395&rep=rep1&type=pdf

**Comment by coderfromhere** [comment]
Thanks a lot!

**Comment by ddssff** [comment]
Thank me with a pull request!

**Comment by coderfromhere** [comment]
you mentioned the link is valid for a moment, is it relatively permanent to be merged?

**Comment by ddssff** [comment]
I don't know.  I would favor dropping the pdf into the repository rather than a link, though I'm not sure how to then link to that in the README.

**Comment by eelco** [comment]
Apologies, this has been fixed now!
